### ISSUE TITLE
How much data is used for fine tuning?

### ISSUE THREAD

**Issue by hengjiUSTC** [danielgross/LlamaAcademy#3]
Hope to know, after instruction generation process, how much instructions is generated to finetune Vincua?

**Comment by huyphan168** [comment]
The config file recommends at least 200 examples. Personally, I think you should generate data as much as possible for high quality generation.

**Comment by hengjiUSTC** [comment]
Oh crazy! I thought finetuning need something close to 2-3k to be useful before.
